substitutions:
  device: "freshmatic-living-room"
  spray_pin: "D8"
  interval1: "5"
  interval2: "15"
  interval3: "30"
  interval4: "60"
  interval5: "120"
  squirt_pulse: "150ms"
  maxSquirts: "2500"

esphome:
  name: ${device}

esp8266:
  board: d1_mini
  restore_from_flash: true

logger:
  logs:
    binary_sensor: NONE
    sensor: NONE
    switch: NONE
    component: NONE

api:
  encryption:
    key: !secret freshmatic_api_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: ${device}
    password: ${device}

web_server:
  port: 80
  version: 3
  local: true

globals:
  - id: squirts
    type: float
    restore_value: yes
  - id: press_duration
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_time
    type: float
    restore_value: no
    initial_value: '0'

script:
  - id: spray_action
    mode: single
    then:
      - logger.log: "Spray action triggered!"
      - lambda: |-
          pinMode($spray_pin, OUTPUT);
          digitalWrite($spray_pin, HIGH);
          delay(150);
          digitalWrite($spray_pin, LOW);
          id(squirts) += 1;

  - id: squirtTimer
    mode: restart
    then:
      - while:
          condition:
            lambda: 'return id(intervalSelect).current_option() != "Off";'
          then:
            - delay: !lambda 'return atoi(id(intervalSelect).current_option().c_str()) * 60000;'
            - button.press: theSquirter

binary_sensor:
  - platform: gpio
    name: "${device} button"
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - lambda: |-
            id(button_press_time) = millis();
    on_release:
      then:
        - lambda: |-
            float press_duration = (millis() - id(button_press_time)) / 1000.0;
            if (press_duration >= 5.0) {
              id(squirts) = 0;
              ESP_LOGI("reset", "Spray counter reset to 0!");
            } else {
              id(spray_action).execute();
            }

select:
  - platform: template
    id: intervalSelect
    name: "${device} interval"
    icon: mdi:timer-outline
    optimistic: true
    restore_value: true
    options:
      - "Off"
      - "${interval1} Minutes"
      - "${interval2} Minutes"
      - "${interval3} Minutes"
      - "${interval4} Minutes"
      - "${interval5} Minutes"
    on_value:
      then:
        - script.execute: squirtTimer

button:
  - platform: template
    name: "${device} spray"
    icon: mdi:spray
    id: theSquirter
    on_press:
      then:
        - script.execute: spray_action

  - platform: template
    name: "${device} Reset Spray Count"
    icon: mdi:counter-reset
    id: reset_spray_count
    on_press:
      then:
        - lambda: |-
            id(squirts) = 0;

sensor:
  - platform: template
    id: can_level
    name: "${device} can"
    device_class: volume
    unit_of_measurement: "%"
    update_interval: ${interval1} min
    lambda: |-
      return (($maxSquirts - id(squirts)) / $maxSquirts) * 100;

  - platform: wifi_signal
    name: "${device} WiFi Strength"
    update_interval: 60s

status_led:
  pin:
    number: D4
    inverted: yes